ENV_FILE='.env'

# prepairing
CONTEXT_ROOT="$(realpath .)"
CONTEXT_API="$CONTEXT_ROOT/api"
CONTEXT_DB="$CONTEXT_ROOT/scripts"
CONTEXT_TASK="$CONTEXT_API"

cat > $ENV_FILE <<EOF
# base settings
CONTEXT_ROOT=$CONTEXT_ROOT
CONTEXT_TASK=$CONTEXT_TASK
CONTEXT_DB=$CONTEXT_DB

# database settings
POSTGRES_USER=postgres
POSTGRES_PASSWORD=Aa123456

PGADMIN_DEFAULT_EMAIL=phamtanvinh.me@gmail.com
PGADMIN_DEFAULT_PASSWORD=Aa123456

# task settings
BROKER_REDIS_DB=0
RESULT_REDIS_DB=1

# kong settings
KONG_PG_DATABASE=postgres
KONG_PG_USER=kong
KONG_PG_PASSWORD=Aa123456

KONGA_DB=konga

EOF