version: '3'
services:
  backend-api:
    container_name: backend-api
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - backend-net
    ports:
      - '5000:5000'
    environment:
      POSTGRES_HOST: blog-api
      POSTGRES_PORT: 5432
      POSTGRES_DB: blog
      POSTGRES_USER: blog_api
      POSTGRES_PASSWORD: Aa123456
      REDIS_HOST: task-queue
      REDIS_PORT: 6379

    # restart: on-failure

networks:
  backend-net:
    external: true
