version: '3'
services:
  balancer-backend:
    container_name: balancer-backend
    build:
      context: ./d.balancer/nginx
    # ports:
    #   - 8080:80
    environment:
      CONSUL_HOST: 'consul-server'
    networks:
      - backend-net
    restart: on-failure

networks:
  backend-net:
    external: true