version: '3'
services:
  consul:
    container_name: consul
    image: progrium/consul
    command: -server -bootstrap -advertise ${HOST_IP}
    labels:
      SERVICE_IGNORE: 'yes'
    # ports:
    #   - 8500:8500
    expose:
      - 8500
    environment:
      VIRTUAL_HOST: ${PROXY_BALANCER_CONSUL}
      VIRTUAL_PORT: 8500
    networks:
      - backend-net
      - proxy-net

  consul-registrator:
    container_name: consul-registrator
    image: gliderlabs/registrator:latest
    command: '-internal consul://consul:8500'
    links:
      - consul:consul
    volumes:
      - ${DOCKER_SOCKET}:/tmp/docker.sock
    networks:
      - backend-net

networks:
  backend-net:
    external: true
  proxy-net:
    external: true
