version: '3'
services:
  blog-db:
    container_name: blog-db
    build:
      context: ${CONTEXT_DB}
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db-net
      - backend-net
    ports:
      - '5432:5432/tcp'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      VIRTUAL_HOST: ${PROXY_PGADMIN}
    depends_on:
      - blog-db
    links:
      - blog-db
    networks:
      - db-net
      - backend-net
    # ports:
    #   - '8088:80/tcp'
    volumes:
      - db_data:/var/lib/pgadmin
    restart: on-failure

networks:
  db-net:
  backend-net:
    external: true

volumes:
  db_data:
    external: true
