version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - '80:80/tcp'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - backend-net

networks:
  backend-net:
    external: true