version: '3'
services:
  portainer: 
    container_name: portainer
    image: portainer/portainer
    volumes:
      - ${DOCKER_SOCKET}:${DOCKER_SOCKET}
      - portainer_data:/data
    networks:
      - proxy-net
    environment:
      VIRTUAL_HOST: ${PROXY_PORTAINER}

volumes:
  portainer_data:
    external: true

networks:
  proxy-net:
    external: true
