version: '3'
services:
  proxy-nginx:
    container_name: proxy-nginx
    image: jwilder/nginx-proxy:alpine
    ports:
      - '80:80/tcp'
    volumes:
      - ${DOCKER_SOCKET}:/tmp/docker.sock:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true