version: '3'

services:
  task-queue:
    image: redis
    container_name: task-queue
    networks:
      - task-net
      - backend-net
    volumes:
      - task_data

  task-worker:
    container_name: task-worker
    image: victor-task
    depends_on:
      - task-queue
    links:
      - task-queue
    networks:
      - task-net
    environment:
      BROKER_URL: 'redis://task-queue/${BROKER_REDIS_DB}'
      CELERY_RESULT_BACKEND: 'redis://task-queue/${RESULT_REDIS_DB}'

  task-monitor:
    container_name: task-monitor
    image: victor-task
    # ports:
    #   - '5555:5555'
    entrypoint: flower
    command: -A tasks.celery --port=5555 --broker=redis://task-queue/${BROKER_REDIS_DB}
    depends_on:
      - task-queue
    networks:
      - task-net
      - proxy-net
    environment:
      VIRTUAL_HOST: ${PROXY_TASK_MONITOR}
    restart: on-failure

networks:
  task-net:
  backend-net:
    external: true
  proxy-net:
    external: true

volumes:
  task_data:
    external: true