version: '3'

services:
  task-queue:
    image: redis
    container_name: task-queue
    networks:
      - task-net
      - backend-net

  task-worker:
    container_name: task-worker
    build:
      context: ${CONTEXT_TASK}
      dockerfile: ./monitor/Dockerfile
    depends_on:
      - task-queue
    links:
      - task-queue
    networks:
      - task-net
    environment:
      BROKER_URL: 'redis://task-queue/${BROKER_REDIS_DB}'
      CELERY_RESULT_BACKEND: 'redis://task-queue/${RESULT_REDIS_DB}'

  task-monitor:
    container_name: task-monitor
    build:
      context: ${CONTEXT_TASK}
      dockerfile: ./monitor/Dockerfile
    # ports:
    #   - '5555:5555'
    entrypoint: flower
    command: -A tasks.celery --port=5555 --broker=redis://task-queue/${BROKER_REDIS_DB}
    depends_on:
      - task-queue
    networks:
      - task-net
      - backend-net
    environment:
      VIRTUAL_HOST: ${PROXY_TASK_MONITOR}
    restart: on-failure

networks:
  task-net:
  backend-net:
    external: true
